name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - name: Commit and tag dist files
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@github.com"
          yarn version --minor --no-git-tag-version
          git add -A
          TAG="v$(node -p "require('./package.json').version")"
          git commit -m "- chore: version bump ($TAG)"
          git tag "$TAG-dev"
          git push --tags origin $GITHUB_REF
