name: Test and lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: '12'
      - run: yarn install
      - run: yarn lint
      - run: yarn test
